---
# Install Riemann packages on redhat base distributions.

- name: Uninstall existing Riemann package.
  yum: name=riemann state=absent

- name: Install Riemann from rpm.
  yum: name=https://aphyr.com/riemann/riemann-0.2.11-1.noarch.rpm state=present

- name: Reload the service daemon.
  command: systemctl daemon-reload

- name: Configure Riemann.
  include: riemann.yml
